extends:
  - airbnb-typescript
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:jsx-a11y/recommended

plugins:
  - '@typescript-eslint/eslint-plugin'

parser: '@typescript-eslint/parser'

parserOptions:
  project: ./tsconfig.json

rules:
  '@typescript-eslint/ban-ts-ignore': off
  react/prop-types: off
  object-curly-newline: off
