extends:
  - airbnb-typescript
  - plugin:@typescript-eslint/eslint-recommended

plugins:
  - '@typescript-eslint/eslint-plugin'

parser: '@typescript-eslint/parser'

parserOptions:
  project: ./tsconfig.json

rules:
  max-len:
    - error
    - 120
  '@typescript-eslint/ban-ts-comment': off
  react/prop-types: off
  object-curly-newline: off
  '@typescript-eslint/explicit-function-return-type': off
  jsx-quotes:
    - error
    - prefer-single
  no-multiple-empty-lines:
    - error
    - max: 2
